[[mixins]]
config = "macos_input_fixes.client.mixins.json"

[[mods]]
modId = "macos_input_fixes"
version = "1.0"
displayName = "MacOS Input Fixes"
authors = "Hamarb123"
description = "Fixes Minecraft input issues on macOS."
